"""empty message

Revision ID: 4e00a56e626a
Revises: 
Create Date: 2023-04-15 03:24:53.868189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e00a56e626a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_first_name'), ['first_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_last_name'), ['last_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_username'), ['username'], unique=True)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=140), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_username'))
        batch_op.drop_index(batch_op.f('ix_client_last_name'))
        batch_op.drop_index(batch_op.f('ix_client_first_name'))
        batch_op.drop_index(batch_op.f('ix_client_email'))

    op.drop_table('client')
    # ### end Alembic commands ###
